language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

script:
   - mvn -Ddocker.keepContainer -DskipTests=false -DskipTests=true -B clean package
   #- mvn -Ddocker.keepContainer -DskipTests=false -B clean verify coveralls:report