version: 2
jobs:
  build:
    working_directory: ~/DAVe-StoreManager
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          # creating dummy container which will hold a volume with sources
          docker create -v /DAVe-StoreManager --name src circleci/openjdk:8 /bin/true
          # copying sources into this volume
          docker cp ~/DAVe-StoreManager src:/
          # starting application container using this volume
          docker run --volumes-from src -w /DAVe-StoreManager circleci/openjdk:8-jdk mvn -B clean verify
