version: 2
jobs:
  build:
    working_directory: ~/DAVe-StoreManager
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          environment:
            PROJECT_NAME: DAVe-StoreManager
          command: |
            # store our env variables
            set | grep ^DOCKER > /tmp/env.list
            docker run -d -it --name dave --env-file /tmp/env.list circleci/openjdk:8-jdk /bin/bash
            docker cp ~/${PROJECT_NAME} dave:/home/circleci
            docker cp $DOCKER_CERT_PATH dave:/tmp
            docker exec dave sh -c "sudo chown -R circleci.circleci $DOCKER_CERT_PATH"
            docker exec dave sh -c "sudo chown -R circleci.circleci ~/${PROJECT_NAME}"
            docker exec dave sh -c "cd ~/${PROJECT_NAME} && mvn -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.organization=$SONARQUBE_ORG -B clean verify sonar:sonar"
            docker cp dave:/home/circleci/${PROJECT_NAME}/target ~/${PROJECT_NAME}
