version: 2
jobs:
  build:
    working_directory: ~/DAVe-StoreManager
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx2048m"
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          # store our env variables
          set | grep ^DOCKER > /tmp/env.list
          docker run -d -it --name dave --env-file /tmp/env.list -w /DAVe-StoreManager circleci/openjdk:8-jdk /bin/bash
          docker cp ~/DAVe-StoreManager dave:/home/circleci
          docker cp $DOCKER_CERT_PATH dave:/tmp
          docker exec dave sh -c "sudo chown -R circleci.circleci $DOCKER_CERT_PATH"
          docker exec dave sh -c "sudo chown -R circleci.circleci ~/DAVe-StoreManager"
          docker exec dave sh -c "cd ~/DAVe-StoreManager && mvn -B -P circle clean verify"
